### ISSUE TITLE
Pull Quads/Stickies off assignment

### ISSUE THREAD

**Issue by mbMosman** [PrimeAcademy/object-group-bonus-calculator#5]
Suggest pulling this off the assignment itself. It could be its own repo, or just introduced by instructors as a separate activity later on. 

Reasons not to do this here:
- With this activity happening earlier (on day 2), we may not have gotten to strengths yet (one of the quad questions)
- This has evolved into more of an individual but work together or pair assignment than a group assignment over time. It would be more effective before a true "group" assignment where they really need to work together to share code & plan.

**Comment by DoctorHowser** [comment]
I think this is a result of the timing change we've seen with the new student life team -- it seems like there's a general schedule of doing the superpowers on the Wednesday after lunch. 

We probably should:
- confirm schedule consistencies with student life team
- either recommend they move the superpowers talk on Tuesday, where it tended to be before, 
or
- Revamp this week of content to have a new group project toward the end of the week?

**Comment by DoctorHowser** [comment]
I've changed it to be 'What do you do when you're stressed' -- could add superpowers later?

**Comment by eschwartz** [comment]
Moved to https://github.com/PrimeAcademy/curriculum-syllabus-master/issues/443
